recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('r<int:pk>/', views.RecipeView.as_view(), name='recipe'),
    path('r<int:pk>/order', views.OrderView.as_view(), name='order'),
]

recipist/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
]

recipes/models.py
from django.db import models


class Recipe(models.Model):
    name = models.CharField(max_length=100, default="Food")
    steps = models.TextField()

class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="Nothing")
    amount = models.FloatField()
    unit = models.CharField(max_length=20)

recipes/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View

from .models import Recipe

class IndexView(generic.ListView):
    template_name = 'recipes/index.html'
    context_object_name = 'recipes_list'
    paginate_by = 10

    def get_queryset(self):
        """Return all existing recipies."""
        return Recipe.objects.all()


class RecipeView(generic.DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'
    

class OrderView(View):
    model = Recipe
    template_name = 'recipes/order.html'

    def get(self, request, pk):
        recipe = get_object_or_404(Recipe, pk=pk)
        return render(request, self.template_name, {'recipe': recipe})

    def post(self, request, pk):
        recipe = get_object_or_404(Recipe, pk=pk)
        return render(request, self.template_name, {'recipe': recipe})

templates/recipes/detail.html
<form action="{% url 'recipes:order' recipe.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ recipe.name }}</h1></legend>
    {% for ingredient in recipe.ingredient_set.all %}
        <input type="checkbox" name="ingredient" id="ingredient{{ forloop.counter }}" value="{{ ingredient.id }}">
        <label for="ingredient{{ forloop.counter }}">{{ ingredient.name }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

{{ recipe.ingredients }}

templates/recipes/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'recipes/style.css' %}">

{% if recipes_list %}
    <ul>
    {% for recipe in recipes_list %}
        <li><a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

templates/recipes/order.html
You just ordered {{ recipe.name }}